---
driver:
  name: docker
  hostname: roundcube.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: roundcube
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - roundcube
  pillars:
    top.sls:
      base:
        "*":
          - roundcube

verifier:
  name: inspec
  sudo: true


platforms:
  - name: <%=ENV['PLATFORM'] || 'ubuntu-xenial'%>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'trevorj/salty-whales:xenial'%>
      platform: ubuntu

suites:

  - name: server
    provisioner:
      pillars-from-files:
        roundcube.sls: tests/pillar/server.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
